export const AppImages = {
  icScore: require('../assets/images/icScore.png'),
  icScoreSelected: require('../assets/images/icScoreSelected.png'),
  icJacpot: require('../assets/images/icJacpot.png'),
  icJackpotSelected: require('../assets/images/icJackpotSelected.png'),
  icMedia: require('../assets/images/icMedia.png'),
  icMediaSelected: require('../assets/images/icMediaSelected.png'),
  icProfile: require('../assets/images/icProfile.png'),
  icProfileSelected: require('../assets/images/icProfileSelected.png'),
  icRivals: require('../assets/images/icRivals.png'),
  icRivalsSeleted: require('../assets/images/icRivalsSeleted.png'),
  icRightArrow: require('../assets/images/icRightArrow.png'),
  icGift: require('../assets/images/icGift.png'),
  icNotification: require('../assets/images/icNotification.png'),
  ic_Search_light: require('../assets/images/ic_Search_light.png'),
  icnMenu: require('../assets/images/icnMenu.png'),
  icFullScreenCorner: require('../assets/images/icFullScreenCorner.png'),
  icUserPic: require('../assets/images/icUserPic.png'),
  ic_expandRightDouble: require('../assets/images/ic_expandRightDouble.png'),
  icBackButton: require('../assets/images/icBackButton.png'),
  icTrendDown: require('../assets/images/icTrendDown.png'),
  icTrendUp: require('../assets/images/icTrendUp.png'),
  icCloseRound: require('../assets/images/icCloseRound.png'),
  icPagger: require('../assets/images/icPagger.png'),
  icUserPicSquare: require('../assets/images/icUserPicSquare.png'),
  icUserPicSquare1: require('../assets/images/icUserPicSquare1.png'),
};
